// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/BubblePlayzTHEREAL/Ron-s-Designs-and-Signs/pkg/meta"

func Base(m meta.PageMeta) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MetaTags(m).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<link rel=\"preload\" href=\"/static/fonts/Inter-Variable.woff2\" as=\"font\" type=\"font/woff2\" crossorigin=\"anonymous\"><link rel=\"stylesheet\" href=\"/static/css/output.css\"><link rel=\"icon\" type=\"image/png\" href=\"/images/logo-transparent.png\"></head><body class=\"min-h-screen bg-gradient-to-br from-primary to-primary-dark text-text\"><header class=\"header\"><a href=\"/\" aria-label=\"Go to homepage\"><img src=\"/images/logo-transparent.png\" alt=\"Ron's Designs and Signs Logo\" class=\"header-logo\"></a><nav id=\"navMenu\" class=\"nav-menu\"><div class=\"nav-overlay\" id=\"navOverlay\"></div><div class=\"nav-content\"><button class=\"nav-close\" id=\"navClose\" aria-label=\"Close menu\"><svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\"></line> <line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\"></line></svg></button> <a href=\"/\" class=\"nav-link\">Home</a> <a href=\"/services\" class=\"nav-link\">Services</a> <a href=\"/gallery\" class=\"nav-link\">Gallery</a> <a href=\"/contact\" class=\"nav-link\">Contact</a></div></nav><button class=\"menu-toggle\" id=\"menuToggle\" aria-label=\"Open menu\"><span></span><span></span><span></span></button></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = mobileMenuScript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main><footer class=\"footer-modern\"><div class=\"footer-container\"><div class=\"footer-column\"><h3 class=\"footer-title\">Business Hours</h3><p class=\"footer-text\">Monday - Friday</p><p class=\"footer-text footer-highlight\">8:00 AM - 5:00 PM</p><p class=\"footer-text mt-2\">Saturday & Sunday</p><p class=\"footer-text\">Closed</p></div><div class=\"footer-column\"><h3 class=\"footer-title\">Quick Links</h3><a href=\"/\" class=\"footer-link\">Home</a> <a href=\"/services\" class=\"footer-link\">Services</a> <a href=\"/gallery\" class=\"footer-link\">Gallery</a> <a href=\"/contact\" class=\"footer-link\">Contact</a></div><div class=\"footer-column\"><h3 class=\"footer-title\">Get In Touch</h3><a href=\"tel:+17155798471\" class=\"footer-link\"><svg class=\"footer-icon\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\"><path d=\"M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328z\"></path></svg> (715) 579-8471</a> <a href=\"mailto:ronsdesigns@hotmail.com\" class=\"footer-link\"><svg class=\"footer-icon\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\"><path d=\"M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z\"></path></svg> ronsdesigns@hotmail.com</a><div class=\"footer-social\"><p class=\"footer-text-sm\">Follow us on social media</p></div></div></div><div class=\"footer-bottom\"><p class=\"footer-copyright\">© 2026 ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(meta.SiteNameFromCtx(ctx))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layouts/base.templ`, Line: 81, Col: 41}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p></div></footer><!-- Brevo Conversations --><script>\n\t\t\t\t(function(d, w, c) {\n\t\t\t\t\tw.BrevoConversationsID = '6967a474020e296c6602e435';\n\t\t\t\t\tw[c] = w[c] || function() {\n\t\t\t\t\t\t(w[c].q = w[c].q || []).push(arguments);\n\t\t\t\t\t};\n\t\t\t\t\tvar s = d.createElement('script');\n\t\t\t\t\ts.async = true;\n\t\t\t\t\ts.src = 'https://conversations-widget.brevo.com/brevo-conversations.js';\n\t\t\t\t\tif (d.head) d.head.appendChild(s);\n\t\t\t\t})(document, window, 'BrevoConversations');\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func mobileMenuScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<script>\n\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\tconst toggle = document.getElementById('menuToggle');\n\t\t\tconst menu = document.getElementById('navMenu');\n\t\t\tconst overlay = document.getElementById('navOverlay');\n\t\t\tconst closeBtn = document.getElementById('navClose');\n\n\t\t\tif (!toggle || !menu || !overlay || !closeBtn) return;\n\n\t\t\tfunction openMenu() {\n\t\t\t\tmenu.classList.add('active');\n\t\t\t\ttoggle.classList.add('active');\n\t\t\t\tdocument.body.style.overflow = 'hidden';\n\t\t\t}\n\n\t\t\tfunction closeMenu() {\n\t\t\t\tmenu.classList.remove('active');\n\t\t\t\ttoggle.classList.remove('active');\n\t\t\t\tdocument.body.style.overflow = '';\n\t\t\t}\n\n\t\t\ttoggle.addEventListener('click', openMenu);\n\t\t\tcloseBtn.addEventListener('click', closeMenu);\n\t\t\toverlay.addEventListener('click', closeMenu);\n\t\t\t\tlink.addEventListener('click', closeMenu);\n\t\t\t});\n\n\t\t\t// Close on ESC key\n\t\t\tdocument.addEventListener('keydown', (e) => {\n\t\t\t\tif (e.key === 'Escape' && menu.classList.contains('active')) {\n\t\t\t\t\tcloseMenu();\n\t\t\t\t}\n\t\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
