package api












































}	e.ServeHTTP(w, r)func Handler(w http.ResponseWriter, r *http.Request) {}	h.RegisterRoutes(e)	h := handler.New(cfg, db, emailSvc)	middleware.Setup(e, cfg)	e.Use(cors.Default())	emailSvc := email.NewService(cfg.BrevoAPIKey, cfg.ContactEmail)	}		os.Exit(1)		slog.Error("failed to connect to database", "error", err)	if err != nil {	db, err := database.New(ctx, cfg.DatabaseURL)	ctx := context.Background()	cfg := config.Load()	e.HideBanner = true	e = echo.New()func init() {var e *echo.Echo)	"github.com/labstack/echo/v4/middleware/cors"	"github.com/labstack/echo/v4"	"ronsdesigns/internal/middleware"	"ronsdesigns/internal/handler"	"ronsdesigns/internal/email"	"ronsdesigns/internal/database"	"ronsdesigns/internal/config"	"os"	"net/http"	"log/slog"	"context"import (package handler